name: etf_crawlling

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Lint with flake8
      run: |
        conda install flake8, pandas, json, requests
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run crawlling
      run: |
        python "crawller.py"
    - name: commit
      run: |
        git config --local user.email "tmdduq9008@gmail.com"
        git config --local user.name "SEUNGTO"
        git add test_resultDict.json
        git commit -mn "Auto - update data"

    - name: push
      uses : ad-m/github-push-action@master
      with :
         branch : 'master'
         github_token : $
